### PR TITLE
Added Flickr8k dataset

### PR DESCRIPTION
**Pull request by michaelbzhu**

### CODE REVIEW

**Comment by tgaddair** [comment]
Hey @michaelbzhu, this looks great, thanks for putting this together.  We just landed a PR to fix the tests, can you rebase and push?

**Comment by michaelbzhu** [comment]
@tgaddair Ok I've rebased the branch history to follow the new upstream commits; although I'm not sure why the build checks aren't appearing.

**Comment by tgaddair** [comment]
Thanks @michaelbzhu, might have something to do with the donation of Ludwig to the Linux Foundation which went through yesterday.  That may have messed up the CI.  I'll take a look.

**Comment by tgaddair** [comment]
Hey @michaelbzhu, the CI integration should be fixed.  Can you try making a whitespace change or similar and pushing again?

**Review by tgaddair — APPROVED** [review]
LGTM!  Thanks for the PR.

**Pull request merged**
