### PR TITLE
GBM: remove distributed=False from RayDMatrix

### PR DESCRIPTION
**Pull request by jppgks**
Ray Datasets are distributed by nature, there should be no need to set this to False

### CODE REVIEW

**Review by tgaddair — APPROVED** [review]

**Comment by justinxzhao** [comment]
I tried this locally and ran into some hanging behavior in some of the integration tests. We may see some tests timeout.

**Comment by arnavgarg1** [comment]
> I tried this locally and ran into some hanging behavior in some of the integration tests. We may see some tests timeout.

Yeah, seems like it is hanging

**Comment by jppgks** [comment]
py-spy dump from the hanging LightGBM actor processes: 
```python-traceback
Process 2216: ray::_RemoteRayLightGBMActor
Python v3.8.16 (/usr/local/bin/python3.8)

Thread 0xFFFF9DCA7D10 (active): "MainThread"
    main_loop (ray/_private/worker.py:756)
    <module> (ray/_private/workers/default_worker.py:237)
Thread 0xFFFF5A1FE1E0 (idle): "ray_import_thread"
    wait (threading.py:306)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:148)
    result (grpc/_channel.py:733)
    _poll_locked (ray/_private/gcs_pubsub.py:249)
    poll (ray/_private/gcs_pubsub.py:385)
    _run (ray/_private/import_thread.py:70)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
Thread 0xFFFF599FD1E0 (active): "Thread-1"
    channel_spin (grpc/_channel.py:1258)
    run (threading.py:870)
    _bootstrap_inner (threading.py:932)
    _bootstrap (threading.py:890)
```

**Comment by jppgks** [comment]
ray seems to be waiting for resources

```
$ ray status
======== Autoscaler status: 2023-02-14 21:22:51.594088 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_24a67d840dc43a734fb8e3fcc4c319749e505202dd9165c4d63e16e1
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 4.0/4.0 CPU (4.0 used of 4.0 reserved in placement groups)
 0.0/1000.0 hyperopt_resources
 0.00/5.640 GiB memory
 0.00/0.146 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 4+ pending tasks/actors
```

**Comment by arnavgarg1** [comment]
Hey @jppgks , I think it's happening because we set parallelism for the processor to 4 in your backend config (2 * 2), which is going to then basically require at least 8 cpus to be available in your cluster. I've set parallelism for data processing down to 1 for now, this should ideally resolve the hanging issue.

**Review by tgaddair — APPROVED** [review]

**Review by arnavgarg1 — APPROVED** [review]

**Pull request merged**
