### PR TITLE
Allow image bytes type during preprocessing

### PR DESCRIPTION
**Pull request by vijayi1**
In image_feature.py, image bytes instance type is handled by all the _read_image_ routines, except for preprocessing. 
added the same bytes instance logic to the _finalize_preprocessing function.
tested the mnist example, with image paths as well as image bytes objects.

### CODE REVIEW

**Review by alexsherstinsky — APPROVED** [review]
LGTM -- @vijayi1 -- thank you very much for this enhancement!

**Review by arnavgarg1 — COMMENTED** [review]
Thanks for the PR! Is it possible to add a simple test?

**Comment by vijayi1** [comment]
I used the following on examples/mnist/ and trained with the df - 

        import pandas as pd
        
        df = mnist.load()
        
        image_bytes = []
        for index, row in df.iterrows():
            img_path = row['image_path']
            f = open(img_path, mode="rb")
            img_bytes = f.read()
            f.close()
            image_bytes.append(img_bytes)
        
        df_bytes = pd.DataFrame.from_dict({'image_path':image_bytes})
        
        # replace image file paths with image bytes
        df = df.drop(['image_path'],axis=1)
        df = pd.concat([df, df_bytes], axis=1)
        
        #print(df.head())
        #df.to_parquet("temp.parquet")

**Comment by arnavgarg1** [comment]
Sounds good!

**Pull request merged**
