### PR TITLE
Add unit tests for image utils unet functions

### PR DESCRIPTION
**Pull request by vijayi1**
This is a follow up to PR 3913. 
It adds unit tests for the image utils functions added by that PR.

### CODE REVIEW

**Review by justinxzhao — APPROVED** [review]
Thank you!

**Comment by justinxzhao** [comment]
The regression tests are flaky, however it looks like there's another dependency issue going on with torch nightly.

**Review by arnavgarg1 — APPROVED** [review]
LGTM! Can you rebase with master and see if the tests pass?

**Comment by vijayi1** [comment]
@arnavgarg1 sure. can you please confirm if the following steps are correct to rebase a PR and make additional changes (if needed),  

To rebase my branch:
git fetch upstream
git rebase upstream/master

To make further code changes:
git add .
git commit
git push -u origin unet-image-utils-tests

**Comment by arnavgarg1** [comment]
@vijayi1 I think that mostly looks correct! I would change the ordering of the steps to be this instead:

1. git fetch upstream 
2. git checkout unet-image-utils-tests (you want to make sure you're on your branch)
3. git rebase upstream/master (rebase onto your branch)

Followed by:
git add .
git commit -m
git push -u origin unet-image-utils-tests

**Comment by vijayi1** [comment]
@arnavgarg1, I followed those steps exactly and got the following error during push,

(dl_venv) [vijayi@sparky01 ludwig]$ git push -u origin unet-image-utils-tests
To github.com:vijayi1/ludwig.git
 ! [rejected]          unet-image-utils-tests -> unet-image-utils-tests (non-fast-forward)
error: failed to push some refs to 'github.com:vijayi1/ludwig.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(dl_venv) [vijayi@sparky01 ludwig]$

**Comment by arnavgarg1** [comment]
@vijayi1 I see. Okay, if you abort the rebase, another option is to just pull the latest master and merge it into your branch - it should achieve roughly the same effect?

**Comment by vijayi1** [comment]
@arnavgarg1, merge completed and I added a few description changes for the docs. the utils tests passed.

**Pull request merged**
