### PR TITLE
Add unet encoder-decoder and image output feature

### PR DESCRIPTION
**Pull request by vijayi1**
# Code Pull Requests

Please provide the following:

- a clear explanation of what your code does
Added a UNet encoder and decoder stack.
Added an image output feature, and image utils to detect pixel classes.
Added an image semantic segmentation example using a kaggle dataset.
Added test cases for encoder, decoder and dataset.
- if applicable, a reference to an issue
- a reproducible test for your PR (code, config and data sample)
Test example included in PR.

### CODE REVIEW

**Comment by vijayi1** [comment]
@justinxzhao, I opened this PR and closed the previous PR 3870 due to git rebase issues. I've addressed your comments in this PR.

I'm attaching some sample results. Each result has the input image, the label mask and a predicted mask. 
1. the camseq example included in the PR (https://www.kaggle.com/datasets/carlolepelaars/camseq-semantic-segmentation)
2. a buildings dataset, with images cropped due to mem limits on my system (https://www.kaggle.com/datasets/sohaibmoradi/segmented-satellite-images-of-buildings)

camseq_0016E5_07959
camseq_0016E5_07959_L
camseq_predicted_0016E5_07959_L
buildings_img_0
buildings_mask_0
buildings_mask_predicted_0

**Comment by vijayi1** [comment]
attached training results for the camseq example above.

camseq_training_log

**Comment by justinxzhao** [comment]
@vijayi1 This is super cool! Thanks for addressing prior comments and putting together the PR. LGTM!

**Review by justinxzhao — APPROVED** [review]

**Review by arnavgarg1 — APPROVED** [review]
PR looks great!! Amazing work! 

If possible, would you be able to add unit tests for the new functions added in `image_utils.py`?

**Comment by vijayi1** [comment]
Thanks for the reviews. @arnavgarg1, I'll create follow up PRs for those two points.

I do not have write access to merge this PR. Please advise on the next step.

**Comment by arnavgarg1** [comment]
@vijayi1 - Sounds good! Will keep a lookout for those PRs. We just merged your PR into master!

**Comment by arnavgarg1** [comment]
Hey @vijayi1! This was a marquee feature in our Ludwig 0.10.0 release and we'd love to give you a shoutout on LinkedIn. Is there a way to connect? My LinkedIn is https://www.linkedin.com/in/arnavgrg/, feel free to connect!

**Comment by vijayi1** [comment]
Hi @arnavgarg1, thanks for the shoutout. I'm not on LinkedIn, but I did lookup the release announcement.

**Comment by arnavgarg1** [comment]
No worries! And glad you were able to see it :) Just wanted to make sure you knew and we really appreciate the contribution!

**Comment by alexsherstinsky** [comment]
@vijayi1 What is your handle in the Ludwig community Slack?  Thank you!

**Comment by vijayi1** [comment]
"Vijay I", I just joined.

**Pull request merged**
