### PR TITLE
Add Python 3.9 support

### PR DESCRIPTION
**Pull request by tgaddair**
Blocked by https://github.com/tensorflow/addons/issues/2188

### CODE REVIEW

**Comment by tgaddair** [comment]
Blocked by TensorFlow Addons not publishing 3.9 wheels.

**Comment by tgaddair** [comment]
https://github.com/tensorflow/addons/issues/2436

**Comment by tgaddair** [comment]
Blocked by https://github.com/ray-project/ray/issues/11287.

**Comment by carlogrisetti** [comment]
@tgaddair https://github.com/ray-project/ray/issues/11287#issuecomment-871863905

**Comment by tgaddair** [comment]
Good catch @carlogrisetti. We want to try to land this for v0.5, so will take another look at this soon.

**Pull request merged**
