### PR TITLE
FEATURE: Collinear numeric feature dectection capability

### PR DESCRIPTION
**Pull request by jimthompson5802**
# Code Pull Requests

This addresses the collinear number feature detection/removal portion of this request #3078.  Specifically, this is the beginning of [this high-level proposed implementation](https://github.com/ludwig-ai/ludwig/issues/3078#issuecomment-1426853737).

### CODE REVIEW

**Comment by jimthompson5802** [comment]
@tgaddair @w4nderlust  I'm following the original suggestion of updating the `DatasetInfo` with results of the collinear analysis.  This results in adding a boolean attribute called `collinear` to `DatasetInfo` `FieldInfo` class
```
class FieldInfo:
    name: str
    dtype: str
    key: str = None
    distinct_values: List = None
    distinct_values_balance: float = 1.0
    num_distinct_values: int = 0
    nonnull_values: int = 0
    image_values: int = 0
    audio_values: int = 0
    avg_words: int = None
    collinear: bool = False
```

**`collinear`** will be
* `True` for all numeric input features that exceed the VIF threshold
* `False` for all other numeric input features as well as non-numeric input features, i.e., categorical, binary, etc, and all output features.

This collinear detection is initiated as part of `automl.create_auto_config()` function.  This seemed to be the most straight-forward place to invoke the collinear detection because the data (as a `pandas` Dataframe) and feature configurations are available.  This is the call
```
    print("create auto config")
    auto_config = create_auto_config(
        dataset=train_df,
        target='target',
        time_limit_s=7200,
        tune_for_memory=False,
        # user_config={'preprocessing': {'split': {'column': 'split', 'type': 'fixed'}}},
    )
```

Here is sample output with detailed logging.

First, the training data
```
read csv file and create dataframe to make non-collinear features
     target  bin_feature cat_feature     num_0     num_1     num_2     num_3     num_4     num_5     num_6      num_7  \
0  0.818871        False     ZHzMJul  0.284863  0.720661  0.426786  0.507589  0.702902  0.864528 -1.336105  -9.536948   
1  0.925743         True     ezgCRdQ  0.628880  0.101502  0.165103  0.245010  0.606496  0.207763  0.122429  -0.867872   
2  0.202091         True    NKRdojqR  0.578028  0.424827  0.909265  0.072261  0.650865  0.962098 -1.231356 -10.502198   
3  0.944273         True    NKRdojqR  0.722605  0.060232  0.208690  0.416775  0.031204  0.848143 -0.016876  -3.703898   
4  0.819696        False    NKRdojqR  0.668191  0.503192  0.511997  0.644018  0.516477  0.432125 -1.525416  -9.444707   

       num_8     num_9  
0   6.532414  4.429250  
1   3.266505  2.911057  
2  10.002952  3.832480  
3   3.193961 -0.557855  
4   6.065774  3.671656  
```

Now is the trace of collinear feature detection
```
Marking collinear features
input numeric features: ['num_0', 'num_1', 'num_2', 'num_3', 'num_4', 'num_5', 'num_6', 'num_7', 'num_8', 'num_9']

vif values: [('num_0', '3.45291'), ('num_1', '6.52182'), ('num_2', '38.28399'), ('num_3', '6.54150'), ('num_4', '12.87512'), ('num_5', '8.74938'), ('num_6', '100.07908'), ('num_7', '132.09565'), ('num_8', '52.01259'), ('num_9', '10.00941')]
dropping column num_7
remaining columns: ['num_0', 'num_1', 'num_2', 'num_3', 'num_4', 'num_5', 'num_6', 'num_8', 'num_9']

vif values: [('num_0', '3.45266'), ('num_1', '6.51750'), ('num_2', '38.20269'), ('num_3', '6.52146'), ('num_4', '12.87357'), ('num_5', '3.42894'), ('num_6', '4.04081'), ('num_8', '51.90932'), ('num_9', '10.00927')]
dropping column num_8
remaining columns: ['num_0', 'num_1', 'num_2', 'num_3', 'num_4', 'num_5', 'num_6', 'num_9']

vif values: [('num_0', '3.45037'), ('num_1', '6.51301'), ('num_2', '3.28949'), ('num_3', '3.21757'), ('num_4', '12.87106'), ('num_5', '3.42785'), ('num_6', '4.03559'), ('num_9', '10.00927')]
dropping column num_4
remaining columns: ['num_0', 'num_1', 'num_2', 'num_3', 'num_5', 'num_6', 'num_9']

vif values: [('num_0', '3.38211'), ('num_1', '6.39745'), ('num_2', '3.26393'), ('num_3', '3.16650'), ('num_5', '3.41671'), ('num_6', '4.01550'), ('num_9', '2.58593')]
dropping column num_1
remaining columns: ['num_0', 'num_2', 'num_3', 'num_5', 'num_6', 'num_9']

vif values: [('num_0', '3.30523'), ('num_2', '3.18611'), ('num_3', '3.11189'), ('num_5', '3.31676'), ('num_6', '2.12070'), ('num_9', '2.56153')]
collinear status: {'num_0': False, 'num_1': True, 'num_2': False, 'num_3': False, 'num_4': True, 'num_5': False, 'num_6': False, 'num_7': True, 'num_8': True, 'num_9': False}
```

Finally, dump of the `dataset.fields` attribute.  Note that `collinear` attribute is `True` for only features called out in the features with `True` values: 

collinear status: `{'num_0': False, 'num_1': True, 'num_2': False, 'num_3': False, 'num_4': True, 'num_5': False, 'num_6': False, 'num_7': True, 'num_8': True, 'num_9': False}`
```
updated FieldInfo
FieldInfo(name='target', dtype='float64', key=None, distinct_values=array([0.81887108, 0.92574298, 0.20209068, 0.9442726 , 0.8196957 ,
       0.81606694, 0.64906662, 0.47891188, 0.32346985, 0.83635972]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='bin_feature', dtype='bool', key=None, distinct_values=array([False,  True]), distinct_values_balance=0.949317738791423, num_distinct_values=2, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='cat_feature', dtype='object', key=None, distinct_values=array(['ZHzMJul', 'ezgCRdQ', 'NKRdojqR', 'YXcuybeDn', 'LbMYyT', 'zgUrhD',
       'erL', 'gBVBZcEZU', 'dLYeO', 'EusMWsDU'], dtype=object), distinct_values_balance=0.6782608695652174, num_distinct_values=10, nonnull_values=1000, image_values=0, audio_values=0, avg_words=1, collinear=False)
FieldInfo(name='num_0', dtype='float64', key=None, distinct_values=array([0.28486307, 0.62887987, 0.5780283 , 0.72260473, 0.66819096,
       0.41402754, 0.7699508 , 0.06432836, 0.57416933, 0.22385271]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='num_1', dtype='float64', key=None, distinct_values=array([0.72066096, 0.10150164, 0.42482681, 0.06023224, 0.50319219,
       0.63933011, 0.90269023, 0.02547842, 0.6443848 , 0.53395033]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=True)
FieldInfo(name='num_2', dtype='float64', key=None, distinct_values=array([0.42678555, 0.16510325, 0.90926497, 0.20869005, 0.51199692,
       0.53466082, 0.03909088, 0.98011364, 0.72520919, 0.22072975]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='num_3', dtype='float64', key=None, distinct_values=array([0.50758903, 0.24500996, 0.07226141, 0.41677463, 0.64401817,
       0.61813633, 0.08001719, 0.22973432, 0.75733841, 0.06565608]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='num_4', dtype='float64', key=None, distinct_values=array([0.70290164, 0.60649636, 0.65086547, 0.03120377, 0.51647714,
       0.61042302, 0.71896717, 0.24600234, 0.1214478 , 0.29576546]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=True)
FieldInfo(name='num_5', dtype='float64', key=None, distinct_values=array([0.86452768, 0.20776345, 0.96209805, 0.84814288, 0.43212539,
       0.79604272, 0.42430939, 0.36390178, 0.55517521, 0.24796003]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='num_6', dtype='float64', key=None, distinct_values=array([-1.33610486,  0.12242855, -1.23135553, -0.01687616, -1.52541607,
       -0.84822663, -0.94668238,  1.82035722, -0.76389782, -1.15461709]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
FieldInfo(name='num_7', dtype='float64', key=None, distinct_values=array([ -9.53694829,  -0.86787229, -10.50219757,  -3.70389844,
        -9.44470725,  -7.72003606,  -7.19178419,   7.69110374,
        -6.09640616,  -7.53172524]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=True)
FieldInfo(name='num_8', dtype='float64', key=None, distinct_values=array([ 6.53241366,  3.26650525, 10.00295218,  3.19396121,  6.06577424,
        7.62593692, -1.14255976, 12.22041699,  7.77864898,  1.9495353 ]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=True)
FieldInfo(name='num_9', dtype='float64', key=None, distinct_values=array([ 4.42925038,  2.91105742,  3.83248021, -0.55785452,  3.67165617,
        2.24089904,  6.72805491,  2.6401106 ,  1.73124477,  3.21775814]), distinct_values_balance=1.0, num_distinct_values=1000, nonnull_values=1000, image_values=0, audio_values=0, avg_words=None, collinear=False)
```

Assuming this looks good, then I believe the next step is to have `automl` generate a model configuration file **WITHOUT**  numeric input features where `collinear` set to `True`.  This brings up these questions:

* If this is correct, how do want to control this?  I'm assuming there will be times that leaving in the collinear features may make sense, such as when a user wants to compare model performance.  In particular, I'm not sure how this part of the process will interact with the Predibase UI.

* How should the VIF threshold be specified.  I was initially thinking as a global `preprocessing` parameter.  Howver, if we stay with the `create_auto_config()` implementation, the `preprocessing` section does not exist.  Should this threshold be a new parameter for `create_auto_config`?

Let me know what you think.

**Comment by jimthompson5802** [comment]
Took a stab at one way to control whether to perform or not perform collinear feature detection and elimiation.  Added paramter `collinear_threshold` to `create_auto_config()` function.  here is definition of the parameter:

```
    collinear_threshold: Optional[float] = None,  # TODO: (jmt) confirm this is correct approach
```

If `None`, then no collinear detection is performed.  If value is float, that value is the threshold for flagging collinear numeric features.

With this construct, we can build a Ludwig config file that contains or not contains collinear numeric features.   Successfully run `model.experiment()` with both of the following config files.  NOTE: differences in the `input_features` section.

**INCLUDING COLLINEAR FEATURES**
```
WITH COLLINEAR FEATURES
{   'combiner': {'type': 'tabnet'},
    'hyperopt': {   'executor': {   'cpu_resources_per_trial': 1,
                                    'num_samples': 10,
                                    'scheduler': {   'grace_period': 72,
                                                     'max_t': 7200,
                                                     'reduction_factor': 5,
                                                     'time_attr': 'time_total_s',
                                                     'type': 'async_hyperband'},
                                    'time_budget_s': 7200,
                                    'type': 'ray'},
                    'goal': 'minimize',
                    'metric': 'mean_squared_error',
                    'output_feature': 'target',
                    'parameters': {   'combiner.bn_momentum': {   'categories': [0.4, 0.3, 0.2, 0.1, 0.05, 0.02],
                                                                  'space': 'choice'},
                                      'combiner.bn_virtual_bs': {   'categories': [256, 512, 1024, 2048, 4096],
                                                                    'space': 'choice'},
                                      'combiner.num_steps': {   'categories': [3, 4, 5, 6, 7, 8, 9, 10],
                                                                'space': 'choice'},
                                      'combiner.output_size': {   'categories': [8, 16, 24, 32, 64, 128],
                                                                  'space': 'choice'},
                                      'combiner.relaxation_factor': {   'categories': [1.0, 1.2, 1.5, 2.0],
                                                                        'space': 'choice'},
                                      'combiner.size': {'categories': [8, 16, 24, 32, 64], 'space': 'choice'},
                                      'combiner.sparsity': {   'categories': [0.0, 1e-06, 0.0001, 0.001, 0.01, 0.1],
                                                               'space': 'choice'},
                                      'trainer.decay_rate': {'categories': [0.8, 0.9, 0.95], 'space': 'choice'},
                                      'trainer.decay_steps': {   'categories': [500, 2000, 8000, 10000, 20000],
                                                                 'space': 'choice'},
                                      'trainer.learning_rate': {   'categories': [0.005, 0.01, 0.02, 0.025],
                                                                   'space': 'choice'}},
                    'search_alg': {'random_state_seed': 42, 'type': 'hyperopt'}},
    'input_features': [   {'column': 'bin_feature', 'name': 'bin_feature', 'type': 'binary'},
                          {'column': 'cat_feature', 'name': 'cat_feature', 'type': 'category'},
                          {'column': 'num_0', 'name': 'num_0', 'type': 'number'},
                          {'column': 'num_1', 'name': 'num_1', 'type': 'number'},
                          {'column': 'num_2', 'name': 'num_2', 'type': 'number'},
                          {'column': 'num_3', 'name': 'num_3', 'type': 'number'},
                          {'column': 'num_4', 'name': 'num_4', 'type': 'number'},
                          {'column': 'num_5', 'name': 'num_5', 'type': 'number'},
                          {'column': 'num_6', 'name': 'num_6', 'type': 'number'},
                          {'column': 'num_7', 'name': 'num_7', 'type': 'number'},
                          {'column': 'num_8', 'name': 'num_8', 'type': 'number'},
                          {'column': 'num_9', 'name': 'num_9', 'type': 'number'}],
    'output_features': [{'column': 'target', 'name': 'target', 'type': 'number'}],
    'trainer': {   'batch_size': 'auto',
                   'learning_rate': 0.001,
                   'learning_rate_scaling': 'sqrt',
                   'learning_rate_scheduler': {'decay': 'exponential', 'decay_rate': 0.8, 'decay_steps': 20000},
                   'optimizer': {'type': 'adam'},
                   'validation_field': 'target',
                   'validation_metric': 'mean_squared_error'}}
``` 

** EXCLUDING COLLINEAR FEATURES**
```
WITHOUT COLLINEAR FEATURES
{   'combiner': {'type': 'tabnet'},
    'hyperopt': {   'executor': {   'cpu_resources_per_trial': 1,
                                    'num_samples': 10,
                                    'scheduler': {   'grace_period': 72,
                                                     'max_t': 7200,
                                                     'reduction_factor': 5,
                                                     'time_attr': 'time_total_s',
                                                     'type': 'async_hyperband'},
                                    'time_budget_s': 7200,
                                    'type': 'ray'},
                    'goal': 'minimize',
                    'metric': 'mean_squared_error',
                    'output_feature': 'target',
                    'parameters': {   'combiner.bn_momentum': {   'categories': [0.4, 0.3, 0.2, 0.1, 0.05, 0.02],
                                                                  'space': 'choice'},
                                      'combiner.bn_virtual_bs': {   'categories': [256, 512, 1024, 2048, 4096],
                                                                    'space': 'choice'},
                                      'combiner.num_steps': {   'categories': [3, 4, 5, 6, 7, 8, 9, 10],
                                                                'space': 'choice'},
                                      'combiner.output_size': {   'categories': [8, 16, 24, 32, 64, 128],
                                                                  'space': 'choice'},
                                      'combiner.relaxation_factor': {   'categories': [1.0, 1.2, 1.5, 2.0],
                                                                        'space': 'choice'},
                                      'combiner.size': {'categories': [8, 16, 24, 32, 64], 'space': 'choice'},
                                      'combiner.sparsity': {   'categories': [0.0, 1e-06, 0.0001, 0.001, 0.01, 0.1],
                                                               'space': 'choice'},
                                      'trainer.decay_rate': {'categories': [0.8, 0.9, 0.95], 'space': 'choice'},
                                      'trainer.decay_steps': {   'categories': [500, 2000, 8000, 10000, 20000],
                                                                 'space': 'choice'},
                                      'trainer.learning_rate': {   'categories': [0.005, 0.01, 0.02, 0.025],
                                                                   'space': 'choice'}},
                    'search_alg': {'random_state_seed': 42, 'type': 'hyperopt'}},
    'input_features': [   {'column': 'bin_feature', 'name': 'bin_feature', 'type': 'binary'},
                          {'column': 'cat_feature', 'name': 'cat_feature', 'type': 'category'},
                          {'column': 'num_0', 'name': 'num_0', 'type': 'number'},
                          {'column': 'num_2', 'name': 'num_2', 'type': 'number'},
                          {'column': 'num_3', 'name': 'num_3', 'type': 'number'},
                          {'column': 'num_5', 'name': 'num_5', 'type': 'number'},
                          {'column': 'num_6', 'name': 'num_6', 'type': 'number'},
                          {'column': 'num_9', 'name': 'num_9', 'type': 'number'}],
    'output_features': [{'column': 'target', 'name': 'target', 'type': 'number'}],
    'trainer': {   'batch_size': 'auto',
                   'learning_rate': 0.001,
                   'learning_rate_scaling': 'sqrt',
                   'learning_rate_scheduler': {'decay': 'exponential', 'decay_rate': 0.8, 'decay_steps': 20000},
                   'optimizer': {'type': 'adam'},
                   'validation_field': 'target',
                   'validation_metric': 'mean_squared_error'}}

```

Let me know what you think.  I'm taking a pause to get feedback.

**Comment by w4nderlust** [comment]
This makes sense to me @jimthompson5802 .
I would make `_mark_collinear_features` a first class citizen though, with an exposed API that developers can use.
Additionally, i think it may be valuable to provide the vif scores in the info objects as one may want to see them for understanding their data.

I think where it is positioned in automl is great. I'm noodling on adding it ALSO as a preprocessing parameter and reusing the same function within the Ludwig preprocessing, as that would allow to filter out those features also within a regular training process, but I'm still not very sure yet.

**Comment by jimthompson5802** [comment]
@w4nderlust   thank you for the quick feedback.  

re: 

> I would make _mark_collinear_features a first class citizen though, with an exposed API that developers can use.

I'll change function name to `mark_collinear_features` and decorate it with @DeveloperAPI

> Additionally, i think it may be valuable to provide the vif scores in the info objects as one may want to see them for understanding their data.

I can add the VIF score to `FieldInfo`.   I just want to point out that the VIF score for a feature will vary duing the run of `mark_collinear_features` as collinear features are "eliminated".    For example here is how one feature's VIF score evolved before it was eliminated:
```
('col_6', False, '350.11345')
('col_6', False, '9.45245')
('col_6', False, '9.35103')
('col_6', False, '8.31199')
('col_6', False, '8.30993')
('col_6', False, '6.94881')  # eliminated at this point, this score was the maximum of all other features' VIF scores
'col_6': {'collinear': True, 'vif': 6.948806450173743},   # values that will be recorded in FieldInfo
```

Here is an example of a feature that was not deemed collinear
```
('col_0', False, '1.11149')
('col_0', False, '1.10165')
('col_0', False, '1.10165')
('col_0', False, '1.09965')
('col_0', False, '1.09880')
('col_0', False, '1.06508')
('col_0', False, '1.06434')
{'col_0': {'collinear': False, 'vif': 1.0643432112707747}   # values that will be recorded in FieldInfo
```

Here are the final results for all features.  Features that are marked `True`, the VIF score is the one that was the maximum that exceeded the threshold value.  Features marked `False` VIF score is the last one computed for it.
```
collinear flags:
{'col_0': {'collinear': False, 'vif': 1.0643432112707747}, 
'col_1': {'collinear': True, 'vif': 46.405115684565445}, 
'col_2': {'collinear': False, 'vif': 1.1000018967499583}, 
'col_3': {'collinear': False, 'vif': 1.0636374270209146}, 
'col_4': {'collinear': False, 'vif': 1.0556924040990447}, 
'col_5': {'collinear': False, 'vif': 1.061142659319984}, 
'col_6': {'collinear': True, 'vif': 6.948806450173743}, 
'col_7': {'collinear': True, 'vif': 359.4841883237641}, 
'col_8': {'collinear': True, 'vif': 110.86456900733162}, 
'col_9': {'collinear': True, 'vif': 26.986192008033193}, 
'col_10': {'collinear': False, 'vif': 2.9222684028274855}, 
'col_11': {'collinear': False, 'vif': 3.774711612519083}, 
'col_12': {'collinear': False, 'vif': 4.362880721694002}, 
'col_13': {'collinear': True, 'vif': 11.66399329865986}}
```

> I'm noodling on adding it ALSO as a preprocessing parameter and reusing the same function within the Ludwig preprocessing, as that would allow to filter out those features also within a regular training process, but I'm still not very sure yet.

It is good you brought up "preprocessing".  With the current implementation, the `statsmodels` function we are using `variance_inflastion_factor` will raise an exception if there are any missing values, e.g.,
```
Traceback (most recent call last):
  File "/opt/project/sandbox/testbed_sandbox.py", line 134, in <module>
    auto_config = create_auto_config(
  File "/opt/project/ludwig/automl/automl.py", line 281, in create_auto_config
    collinear_flags = _mark_collinear_features(dataset, features_config, collinear_threshold)
  File "/opt/project/ludwig/automl/automl.py", line 431, in _mark_collinear_features
    vif = [variance_inflation_factor(X_arr, ix) for ix in array_indices]
  File "/opt/project/ludwig/automl/automl.py", line 431, in <listcomp>
    vif = [variance_inflation_factor(X_arr, ix) for ix in array_indices]
  File "/usr/local/lib/python3.9/site-packages/statsmodels/stats/outliers_influence.py", line 194, in variance_inflation_factor
    r_squared_i = OLS(x_i, x_noti).fit().rsquared
  File "/usr/local/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 906, in __init__
    super(OLS, self).__init__(endog, exog, missing=missing,
  File "/usr/local/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 733, in __init__
    super(WLS, self).__init__(endog, exog, missing=missing,
  File "/usr/local/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 190, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/model.py", line 267, in __init__
    super().__init__(endog, exog, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/model.py", line 92, in __init__
    self.data = self._handle_data(endog, exog, missing, hasconst,
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/model.py", line 132, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/data.py", line 700, in handle_data
    return klass(endog, exog=exog, missing=missing, hasconst=hasconst,
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/data.py", line 88, in __init__
    self._handle_constant(hasconst)
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/data.py", line 134, in _handle_constant
    raise MissingDataError('exog contains inf or nans')
statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans
```

One advantage of the current approach of not using the current Ludwig preprocessing machinery is the user is not required to provide a "configuration".  This is less of a setup requirement for using automl.   Just toss the data as-is to Ludwig's automl functions.

OTOH, incorporating more advance capabilities, like VIF, may necessitate adding some minimal pre-processing functions under the cover of automl.

At minimum, for the short-term, we can trap exceptions in the `variance_inflation_factor()` and generate a "friendly" message about checking for missing values or non-numeric values in what should be "numbers".

**Comment by jimthompson5802** [comment]
I had one more comment re: preprocessing

>...as that would allow to filter out those features also within a regular training process, but I'm still not very sure yet.

This was the initial approach I thought to take.  I was looking at what it would take to "filter out those features" and these questions/comments came up.

* Is the Input feature method `disable()` intended to support eliminating a feature at during run-time?  From I can see, `disable()` sets an `InputFeature` attribute called `active` to `False`.  

* I don't see reference to the `active` flag in any other part of Ludwig to use or not use an input feature in training or evalation or prediction.

**Comment by w4nderlust** [comment]
@jimthompson5802 regarding the scores changing over time, I agree with your method of reporting, which I can summarize as "the score when a feature was eliminated or at the final round for features that have not been eliminated" if i understand correctly.
Regarding the missin values, that is a good point indeed, and a good reason for having the function used in both places, as within the training process the data would have been already cleaned from nans and maybe also from missing values if outlier detection is on.But this is a general architectural question, curious what @tgaddair @justinxzhao @ShreyaR think about it.

**Comment by jimthompson5802** [comment]
@w4nderlust   you are correct in the interpertation of the reported VIF score.

re: missing values...I'll wait for feedback from others.  In the meantime, I added a more specific message about missing values.

```
<<<< removed earlier stack trace>>> 
 File "/usr/local/lib/python3.9/site-packages/statsmodels/base/data.py", line 88, in __init__
    self._handle_constant(hasconst)
  File "/usr/local/lib/python3.9/site-packages/statsmodels/base/data.py", line 134, in _handle_constant
    raise MissingDataError('exog contains inf or nans')
statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/sandbox/testbed_sandbox.py", line 134, in <module>
    auto_config = create_auto_config(
  File "/opt/project/ludwig/automl/automl.py", line 288, in create_auto_config
    collinear_flags = mark_collinear_features(dataset, features_config, collinear_threshold)
  File "/opt/project/ludwig/automl/automl.py", line 463, in mark_collinear_features
    raise RuntimeError(
RuntimeError: Error computing VIF: exog contains inf or nans. Ensure all numeric input features are valid and there are no missing values.

```

**Pull request closed without merging**
