### PR TITLE
Update schema to correctly reflect supported missing value strategies for different feature types

### PR DESCRIPTION
**Pull request by arnavgarg1**
This PR ensures that Ludwig's schema correctly reflects the missing value strategies supported for input and output feature types in Ludwig.

Notable changes:
- `drop_row` is not supported for input features, but only for output features. This is now removed as an option for input feature types.
- `fill_with_mean` is only supported for number features, so this is removed from the schema options for all other feature types.
- `date` input features only support `fill_with_const`, `bfill` and `ffill`.

Associated documentation update PR: https://github.com/ludwig-ai/ludwig-docs/pull/258

### CODE REVIEW

**Comment by justinxzhao** [comment]
I can see reasons to keep `drop_row` around for input features, for example, as a convenience to automatically drop examples that are missing them.

Curious if other people have thoughts on this.

**Comment by arnavgarg1** [comment]
@justinxzhao That makes sense, but I think that can cause situations where all rows get dropped in the training set after preprocessing which I don't think, is a good outcome. Wdyt?

**Comment by justinxzhao** [comment]
@arnavgarg1 I would expect that to be an odd, but desirable outcome actually, for what's probably a mismatch between the configuration and the user's understanding of their dataset.

**Comment by arnavgarg1** [comment]
@justinxzhao makes sense, added drop row back :)

**Review by justinxzhao — APPROVED** [review]
LGTM

**Pull request merged**
