### PR TITLE
Fixed IterableBatcher incompatibility with ParquetDataset and remote model serialization

### LINKED ISSUE #1134: Parquet dataset does not have a `self.features` attribute, which is needed in the IterableBatcher
**Describe the bug**

The `IterableBatcher` will loop through all the features of a dataset (see[ this line of code](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/batcher/iterable.py#L40)) object via an attribute `self.features` of a `Dataset` object

When the dataset is a parquet dataset (a new feature merged to master in [PR#1090](https://github.com/ludwig-ai/ludwig/commit/01d114ba76667dc52d1673d9be0809ee1e58087c)) (note that parquet is a required format when running ludwig on Ray), the `IteratableBatcher` cannot find this attribute `self.features`.

By going through the code of `parquet.py` I wasn't able to fnd a `self.features` attributes. There is only a self.reshape_features, which does not seem to be compatible with `IterableBatcher`.

**To Reproduce**
See my code on petfinder dataset: https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/train.py#L11

**Expected behavior**
I guess a fix is needed to make IteratableBatcher compatible with ParquetDataset?

**Environment (please complete the following information):**
 - OS: Ubuntu 18
- Python version: 3.6
- Ludwig version: master

**Additional context**

### LINKED ISSUE #1137: `model.set_weights()` with ray backend throws an error when EARLY STOPPING
**Describe the bug**
When training petfinder dataset (see [here ](https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/train.py)for example code) using Ray backend, after a few epochs when EARLY STOPPING is triggered, an error is thrown with the following trace:
```python
Traceback (most recent call last):
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig-petfinder/petfinder-adoption-prediction/train.py", line 34, in <module>
    ) = model.train(dataset=dataset_to_use)
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig/ludwig/api.py", line 480, in train
    save_path=model_dir,
  File "/home/hao.zhang/project/pycharm/ludwig-ray/ludwig/ludwig/backend/ray.py", line 117, in train
    model.set_weights(weights)
  File "/home/hao.zhang/project/pycharm/ludwig-env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1857, in set_weights
    (self.name, len(weights), expected_num_weights, str(weights)[:50]))
ValueError: You called `set_weights(weights)` on layer "ecd" with a weight list of length 30, but the layer was expecting 16 weights. Provided weights: [array([[ 0.3757825 , -0.03104234,  0.8619888 , .....

```

Seems that the `model.set_weights` function under Ray backend has issues because this won't happen in local mode (w/o using Ray backend.)

**Environment (please complete the following information):**
 - OS: Ubuntu 18
- Python version: 3.6
- Ludwig version: master

**Additional context**

### PR DESCRIPTION
**Pull request by tgaddair**
Fixes #1134.

Also attempts to address #1137.

### CODE REVIEW

**Comment by tgaddair** [comment]
Pinned Dask version to workaround https://github.com/ray-project/ray/issues/14992.

**Comment by zhisbug** [comment]
Hi @tgaddair ,

Thanks! I just tested -- it fixes #1134  but not #1137 .

When I disabled the[ image model branch ](https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/config/small.yaml#L59) I still observed the same error when calling `model.set_weights`; when I enable the image branch everything works fine. So I guess it is related with the application?

**Comment by tgaddair** [comment]
Hmm, that's a bummer. Let me pull your branch and try and repro today.

**Comment by tgaddair** [comment]
@zhisbug I'll go ahead and merge this for now since it fixes some tests that were failing on master. We'll leave #1137 open for now.

**Pull request merged**
